"""empty message

Revision ID: 4a4d3bdfd295
Revises: e0746b9b9197
Create Date: 2020-11-03 00:32:41.440832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4d3bdfd295'
down_revision = 'e0746b9b9197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrateur', sa.Column('type', sa.String(length=60), nullable=True))
    op.add_column('etudiant', sa.Column('type', sa.String(length=60), nullable=True))
    op.add_column('professeur', sa.Column('type', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professeur', 'type')
    op.drop_column('etudiant', 'type')
    op.drop_column('administrateur', 'type')
    # ### end Alembic commands ###
