"""empty message

Revision ID: 643dd2463690
Revises: 850c83bc452c
Create Date: 2020-11-01 01:03:54.584848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '643dd2463690'
down_revision = '850c83bc452c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annonce', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonce', sa.Column('type', mysql.VARCHAR(length=60), nullable=True))
    # ### end Alembic commands ###
