"""empty message

Revision ID: e0746b9b9197
Revises: 643dd2463690
Create Date: 2020-11-02 22:53:08.738044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0746b9b9197'
down_revision = '643dd2463690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrateur', sa.Column('adresse', sa.String(length=60), nullable=True))
    op.add_column('administrateur', sa.Column('code_postal', sa.Integer(), nullable=True))
    op.add_column('administrateur', sa.Column('pays', sa.String(length=60), nullable=True))
    op.add_column('administrateur', sa.Column('ville', sa.String(length=60), nullable=True))
    op.add_column('etudiant', sa.Column('adresse', sa.String(length=60), nullable=True))
    op.add_column('etudiant', sa.Column('code_postal', sa.Integer(), nullable=True))
    op.add_column('etudiant', sa.Column('pays', sa.String(length=60), nullable=True))
    op.add_column('etudiant', sa.Column('ville', sa.String(length=60), nullable=True))
    op.add_column('professeur', sa.Column('adresse', sa.String(length=60), nullable=True))
    op.add_column('professeur', sa.Column('code_postal', sa.Integer(), nullable=True))
    op.add_column('professeur', sa.Column('pays', sa.String(length=60), nullable=True))
    op.add_column('professeur', sa.Column('ville', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('professeur', 'ville')
    op.drop_column('professeur', 'pays')
    op.drop_column('professeur', 'code_postal')
    op.drop_column('professeur', 'adresse')
    op.drop_column('etudiant', 'ville')
    op.drop_column('etudiant', 'pays')
    op.drop_column('etudiant', 'code_postal')
    op.drop_column('etudiant', 'adresse')
    op.drop_column('administrateur', 'ville')
    op.drop_column('administrateur', 'pays')
    op.drop_column('administrateur', 'code_postal')
    op.drop_column('administrateur', 'adresse')
    # ### end Alembic commands ###
